
package m1.archi.agence;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserServiceConnectionInscriptionImplService", targetNamespace = "http://service.archi.m1/", wsdlLocation = "http://localhost:8090/agencesservice/A1700315914081/connectionInscription?wsdl")
public class UserServiceConnectionInscriptionImplService
    extends Service
{

    private final static URL USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_EXCEPTION;
    private final static QName USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_QNAME = new QName("http://service.archi.m1/", "UserServiceConnectionInscriptionImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/agencesservice/A1700315914081/connectionInscription?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_WSDL_LOCATION = url;
        USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_EXCEPTION = e;
    }

    public UserServiceConnectionInscriptionImplService() {
        super(__getWsdlLocation(), USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_QNAME);
    }

    public UserServiceConnectionInscriptionImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_QNAME, features);
    }

    public UserServiceConnectionInscriptionImplService(URL wsdlLocation) {
        super(wsdlLocation, USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_QNAME);
    }

    public UserServiceConnectionInscriptionImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_QNAME, features);
    }

    public UserServiceConnectionInscriptionImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServiceConnectionInscriptionImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserServiceConnectionInscription
     */
    @WebEndpoint(name = "UserServiceConnectionInscriptionImplPort")
    public UserServiceConnectionInscription getUserServiceConnectionInscriptionImplPort() {
        return super.getPort(new QName("http://service.archi.m1/", "UserServiceConnectionInscriptionImplPort"), UserServiceConnectionInscription.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServiceConnectionInscription
     */
    @WebEndpoint(name = "UserServiceConnectionInscriptionImplPort")
    public UserServiceConnectionInscription getUserServiceConnectionInscriptionImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.archi.m1/", "UserServiceConnectionInscriptionImplPort"), UserServiceConnectionInscription.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_EXCEPTION!= null) {
            throw USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_EXCEPTION;
        }
        return USERSERVICECONNECTIONINSCRIPTIONIMPLSERVICE_WSDL_LOCATION;
    }

}
